GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9sbGlwb2xsaSIsImlkIjoiNjg5YWU2OGY0OTMzOGM0YzU2NTk1ZGM4IiwiaWF0IjoxNzU0OTgzNzMyfQ.mR0WqUYiMCe8632k1DSXL_0-LuAp692bVYOTuTQHPy0

{
  "title": "Olli's Third Blog Post",
  "author": "Olli Hattivatti",
  "url": "http://example.com/ollis-third-blog-post",
  "likes": 7
}