GET http://localhost:3003/api/users

### Add a new blog
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Test Blog",
    "author": "Test Author",
    "url": "http://example.com/test-blog",
    "likes": 0
}

### Get all blogs
GET http://localhost:3003/api/blogs

### Delete the blog

DELETE http://localhost:3003/api/blogs/6899d7913ac325c4a42acd4d

### Get all blogs
GET http://localhost:3003/api/blogs